export const TOGGLE_MODAL_VISIBILITY = 'TOGGLE_MODAL_VISIBILITY';
export const SET_CURRENT_MODAL_TYPE = 'SET_CURRENT_MODAL_TYPE';
export const SET_INGRIDIENT_IN_MODAL = 'SET_INGRIDIENT_IN_MODAL';
export const SET_ORDER_STATE = 'SET_ORDER_STATE';