const actionTypes = {
    ADD_BUN: 'ADD_BUN',
    ADD_SAUCE: 'ADD_SAUCE',
    ADD_MAIN: 'ADD_MAIN',
    UPDATE_DRAGGABLE_INGRIDIENTS: 'UPDATE_DRAGGABLE_INGRIDIENTS',
    REMOVE_ALL_INGRIDIENTS: 'REMOVE_ALL_INGRIDIENTS',

    GOT_DATA: 'GOT_DATA',
    FETCH_ERROR: 'FETCH_ERROR',
};

export default actionTypes;